// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6nQ2wOrB2gAR7EIbQhxNd8g5pIEkp50g',
    appId: '1:995336050104:android:cab5181af349455046eb4d',
    messagingSenderId: '995336050104',
    projectId: 'aasha-medix-43956',
    storageBucket: 'aasha-medix-43956.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    // NOTE: Replace with your Firebase iOS app credentials
    // Get from: Firebase Console > Project Settings > Your iOS App
    apiKey: 'YOUR_ACTUAL_IOS_API_KEY_HERE',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_APP_HASH',
    messagingSenderId: 'YOUR_SENDER_ID_FROM_FIREBASE_CONSOLE',
    projectId: 'your-aasha-medix-firebase-project',
    storageBucket: 'your-aasha-medix-firebase-project.appspot.com',
    iosBundleId: 'com.aashamedix.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    // NOTE: Replace with your Firebase Web app credentials
    // Get from: Firebase Console > Project Settings > Your Web App
    apiKey: 'AIzaSy_YOUR_ACTUAL_WEB_API_KEY_HERE',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_APP_HASH',
    messagingSenderId: 'YOUR_SENDER_ID_FROM_FIREBASE_CONSOLE',
    projectId: 'your-aasha-medix-firebase-project',
    storageBucket: 'your-aasha-medix-firebase-project.appspot.com',
    authDomain: 'your-aasha-medix-firebase-project.firebaseapp.com',
  );
}
